#!/usr/bin/env sh

SRC_FOLDER=src
OBJ_FOLDER=obj

does_inc_file_exist() {
	if (cd "$(dirname $1)" && [ -f $j ]);
	then
		return 0 # True
	else
		return 1 # False
	fi
}

get_local_inc_files() {
	grep '^#include [<"].*\.h[>"]' "$1" \
		| sed -E 's/^#include [<"](.*)[>"]/\1/g' \
		| while read j;
	do
		if does_inc_file_exist $1 $j;
		then
			echo "$(dirname $1)/$j"
		fi
	done
}

expand_ancestors() {
	while read i;
	do
		 parent=$i
		 while [ ! "$parent" = '.' ];
		 do
			 echo "$parent"
			 parent=$(dirname $parent)
		 done
	 done
}

remove_duplicates() {
	awk '!a[$0]++'
}

MK_OBJ_FDR_TEMPLATE=$(cat <<EOF
	@if [ ! -d "%s" ]; \\
	then        %s     \\
	    \${MKDIR} %s;   \\
	fi
EOF
)

CLEAN_OBJ_FILE_TEMPLATE=$(cat <<EOF
	@if [ -f "%s" ]; \\
	then      %s     \\
	    \${RM} %s;    \\
	fi
EOF
)

CLEAN_OBJ_FDR_TEMPLATE=$(cat <<EOF
	@if [ -d "%s" ];  \\
	then      %s      \\
	    \${RMDIR} %s;  \\
	fi
EOF
)

echo ''
echo '# >>> Generated by gen_make_rules.sh >>>'
echo ''

find $SRC_FOLDER -name '*.c' -printf '%h\n' \
	| expand_ancestors | remove_duplicates \
	| while read i;
do
	if [ "$i" = "$SRC_FOLDER" ];
	then
		continue
	fi

	obj_file=$(echo "$i" | sed -E 's/^'"$SRC_FOLDER"'\//'"$OBJ_FOLDER"'\//')
	parent_depend=$(dirname $obj_file)
	
	printf '%s: %s\n' "$obj_file" "$parent_depend"
	printf "$MK_OBJ_FDR_TEMPLATE\n\n" "$obj_file" \
		"$(echo $obj_file | sed -E 's/./ /g')"    \
		"$obj_file"
done

find $SRC_FOLDER -name '*.c' -printf '%h\n' \
	| expand_ancestors | remove_duplicates \
	| while read i;
do
	if [ "$i" = "$SRC_FOLDER" ];
	then
		continue
	fi

	obj_file=$(echo "$i" | sed -E 's/^'"$SRC_FOLDER"'\//'"$OBJ_FOLDER"'\//')
	parent_depend=$(dirname $obj_file)

	printf 'clean_%s:\n' "$obj_file"
	printf "$CLEAN_OBJ_FDR_TEMPLATE\n\n" "$obj_file" \
		"$(echo $obj_file | sed -E 's/./ /g')" \
		"$obj_file"
done

find $SRC_FOLDER -name '*.c' | while read i;
do
	local_inc_files=$(get_local_inc_files $i)

	obj_file=$(echo "$i" | sed -E 's/'"$SRC_FOLDER"'\/(.*)\.c/'"$OBJ_FOLDER"'\/\1\.o/')
	printf '%s: %s %s %s\n\t$(CC) $(CFLAGS) -c -o $@ %s\n\n' \
		"$obj_file" "$i" "$(dirname $obj_file)" \
		"$(echo $local_inc_files)" "$i"
done

find $SRC_FOLDER -name '*.c' | while read i;
do
	local_inc_files=$(get_local_inc_files $i)

	obj_file=$(echo "$i" | sed -E 's/'"$SRC_FOLDER"'\/(.*)\.c/'"$OBJ_FOLDER"'\/\1\.o/')

	printf 'clean_%s:\n' "$obj_file"
	printf "$CLEAN_OBJ_FILE_TEMPLATE\n\n" "$obj_file" \
		"$(echo $obj_file | sed -E 's/./ /g')" \
		"$obj_file"
done

echo '# <<< Generated by gen_make_rules.sh <<<'
echo ''
