CC=clang
CFLAGS=-Wall -Wpedantic -g 
LD=clang
LDFLAGS= 
LDLIBS= 
exec_out=bin/hello

src_files := src/lang/en/msg.c \
             src/main.c

src_dirs  := src/lang/en \
             src/lang

obj_files := ${src_files:src/%.c=obj/%.o}
obj_dirs  := ${src_dirs:src/%=obj/%}
clean_obj_files := ${obj_files:%=clean_%}
clean_obj_dirs  := ${obj_dirs:%=clean_%}

MKDIR = mkdir
RM    = rm -v
RMDIR = rm -vd

.OBJDIR: ${.CURDIR}
.PHONY: run

.SUFFIXES:
.SUFFIXES: .c .o

$(exec_out): bin ${obj_dirs} ${obj_files}
	$(LD) $(LDFLAGS) -o $@ ${obj_files} $(LDLIBS)

bin:
	@${MKDIR} bin

obj:
	@${MKDIR} obj

run: $(exec_out)
	@-./$(exec_out)

## Non-posix compliant but valid in extended POSIX syntax
# ${clean_obj_files}:
# 	@if [ -f "${@:clean_%=%}" ]; \
# 		then ${RM} ${@:clean_%=%}; \
# 	fi
# 
# ${clean_obj_dirs}:
# 	@if [ -d "${@:clean_%=%}" ]; \
# 		then ${RMDIR} ${@:clean_%=%}; \
# 	fi

clean_${exec_out}: 
	@if [ -f "${exec_out}" ]; \
		then ${RM} ${exec_out}; \
	fi

clean: clean_${exec_out} ${clean_obj_files} ${clean_obj_dirs}

.c.o:
	$(CC) $(CFLAGS) -c -o $@ $<

## Non-POSIX compliant automation rule
## BSD make version
#${obj_files}: ${@:obj/%.o=src/%.c} ${@:H}
#	$(CC) $(CFLAGS) -c -o $@ ${@:obj/%.o=src/%.c}
#
## Non-POSIX compliant automation rule
## BSD make version
#${obj_dirs}: ${@:H}
#	@if [ ! -d "$@" ]; \
#		then ${MKDIR} $@; \
#	fi

## Non-POSIX compliant automation rule
## GNU make version
#obj/%: src/%
#	@${MKDIR} -p $@

## Non-POSIX compliant automation rule
## GNU make version
#obj/%.o: src/%.c obj
#	$(CC) $(CFLAGS) -c -o $@ $<

# ${obj_dirs}: 
# 	@${MKDIR} -p $@

# Below are boilerplate for out-of-source build using POSIX compliant rules
#   (a.k.a) no things like "obj/%.o: src/%.c
#
# To auto-generate the following:
gen_make_rules:
	@$(SHELL) gen_make_rules.sh
#
# However, one might need to enter the header file prerequisites manually..

# >>> Generated by gen_make_rules.sh >>>

obj/lang/en: obj/lang
	@if [ ! -d "obj/lang/en" ]; \
	then                        \
	    ${MKDIR} obj/lang/en;   \
	fi

clean_obj/lang/en:
	@if [ -d "obj/lang/en" ];  \
	then                       \
	    ${RMDIR} obj/lang/en;  \
	fi

obj/lang: obj
	@if [ ! -d "obj/lang" ]; \
	then                     \
	    ${MKDIR} obj/lang;   \
	fi

clean_obj/lang:
	@if [ -d "obj/lang" ];  \
	then                    \
	    ${RMDIR} obj/lang;  \
	fi

obj/main.o: src/main.c obj src/lang/en/msg.h
	$(CC) $(CFLAGS) -c -o $@ src/main.c

clean_obj/main.o:
	@if [ -f "obj/main.o" ]; \
	then                     \
	    ${RM} obj/main.o;    \
	fi

obj/lang/en/msg.o: src/lang/en/msg.c obj/lang/en src/lang/en/msg.h
	$(CC) $(CFLAGS) -c -o $@ src/lang/en/msg.c

clean_obj/lang/en/msg.o:
	@if [ -f "obj/lang/en/msg.o" ]; \
	then                            \
	    ${RM} obj/lang/en/msg.o;    \
	fi

# <<< Generated by gen_make_rules.sh <<<

